name: BFAM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#4f4f4f'
    - '#afafaf'
    - '#8b8b8b'
  brandStrength: 0.9375
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
